name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  url-to-harvest:  # id of input
    description: 'What to harvest'
    required: true
    default: 'https://pkgstore.datahub.io/core/finance-vix/978/datapackage.json'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'